# Generated by Django 6.0.1 on 2026-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_incidentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='media',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incident_media/audio/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('Πυρκαγιά', 'Πυρκαγιά'), ('Τροχαίο', 'Τροχαίο'), ('Διάσωση', 'Διάσωση'), ('Πλημμύρα', 'Πλημμύρα'), ('Άλλο', 'Άλλο')], default='Άλλο', max_length=50),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incident_media/photos/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incident_media/videos/'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
