# Generated by Django 6.0.1 on 2026-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0003_remove_incidentreport_media_incidentreport_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
